version: "3.8"

services:
  nginx:
    build: nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
  login:
    build: login/.
    container_name: login
    volumes:
      - ./web:/var/www/html

